# This stage is used to build the service project.
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Identity.WebApi/Identity.WebApi.csproj", "Identity.WebApi/"]
COPY ["Identity.Infrastructure/Identity.Infrastructure.csproj", "Identity.Infrastructure/"]
COPY ["Identity.Application/Identity.Application.csproj", "Identity.Application/"]
RUN dotnet restore "./Identity.WebApi/Identity.WebApi.csproj"
COPY . .
WORKDIR "/src/Identity.WebApi"
RUN dotnet build "./Identity.WebApi.csproj" -c %BUILD_CONFIGURATION% -o /app/build

# This stage is to update database
WORKDIR /src
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"
ENTRYPOINT [ "dotnet", "ef", "database", "update", "--project", "Identity.Infrastructure", "--startup-project", "Identity.WebApi", "--context", "SecurityDbContext"]